packageExtensions:
  "@webpack-cli/serve@*":
    dependencies:
      webpack-dev-server: 4.11.1

  "@eidellev/inertia-adonisjs@*":
    dependencies:
      "@adonisjs/ace": 11.3.1
      "@adonisjs/http-server": 5.12.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.3.1.cjs
