version: '3.8'

services:
  adonis-app:
    container_name: adonis-app
    restart: always
    build:
      context: .
      target: dependencies
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
      - 8080:8080
    env_file:
      - .env
    volumes:
      - ./:/home/node/app
    command: dumb-init yarn dev --node-args="--inspect=0.0.0.0" --encore-args="--host ${HOST} --port 8080"